// components/SnippetPreview.vue
<template>
  <NuxtLink
    :href="snippet.path"
    class="group text-balance flex flex-col gap-2 focus-visible:ring-transparent"
  >
    <span class="text-body1 text-primary self-start group-focus-within:underline underline-offset-6">
      <SearchHighlight
        hightlighted-class="bg-primary/40"
        :hightlighted-style="{
          color: 'hsl(from var(--color-primary) calc(h + 5) s l)',
        }"
        :text="snippet.title"
        :ranges="titleHighlightRanges"
      />
    </span>
    <span class="text-body2 text-text">
      <SearchHighlight
        hightlighted-class="bg-primary/40"
        :hightlighted-style="{
          color: 'hsl(from var(--color-primary) calc(h + 5) s l)',
        }"
        :text="snippet.description"
        :ranges="descriptionHighlightRanges"
      />
    </span>
    <div class="flex gap-1">
      <Tag
        v-for="tag in snippet.topics"
        :key="tag"
        variant="outlined"
        size="small"
        class="pointer-events-none capitalize"
      >
        {{ tag }}
      </Tag>
    </div>
  </NuxtLink>
</template>

<script lang="ts" setup>
import type { SnippetsCollectionItem } from '@nuxt/content'
import type { HighlightRanges } from '@nozbe/microfuzz'
import SearchHighlight from './SearchHightlight.vue'

const {
  snippet,
  titleHighlightRanges,
  descriptionHighlightRanges,
} = defineProps<{ snippet: SnippetsCollectionItem, titleHighlightRanges: HighlightRanges, descriptionHighlightRanges: HighlightRanges }>()
</script>

<style>

</style>

// components/Snippet/SnippetPreview.tsx
import { type HighlightRanges } from '@nozbe/microfuzz';
import { Highlight } from '@nozbe/microfuzz/react';
import Tag from '@/components/Tag/Tag';
import { type Snippet } from 'content-collections';
import { Link } from '../Link';

type SnippetPreviewProps = {
  snippet: Snippet;
  titleHighlightRanges: HighlightRanges | null;
  descriptionHighlightRanges: HighlightRanges | null;
};

export const SnippetPreview: React.FC<SnippetPreviewProps> = ({
  snippet,
  titleHighlightRanges,
  descriptionHighlightRanges,
}) => {
  return (
    <Link
      href={`/snippets/${snippet.slug}`}
      className="group text-balance flex flex-col gap-2 focus-visible:ring-transparent"
    >
      <span className="text-body1 text-primary self-start group-focus-within:underline underline-offset-6">
        <Highlight
          className="bg-primary/40"
          style={{
            color: 'hsl(from var(--color-primary) calc(h + 5) s l)',
          }}
          text={snippet.title}
          ranges={titleHighlightRanges}
        />
      </span>
      <span className="text-body2 text-text">
        <Highlight
          className="bg-primary/40"
          style={{}}
          text={snippet.description}
          ranges={descriptionHighlightRanges}
        />
      </span>
      <div className="flex gap-1">
        {snippet.topics.map((tag) => (
          <Tag
            key={tag}
            variant="outlined"
            size="small"
            className="pointer-events-none capitalize"
          >
            {tag}
          </Tag>
        ))}
      </div>
    </Link>
  );
};
