// components/SnippetsSearch.vue
<template>
  <div>
    <TextInput
      :value="query"
      placeholder="Поиск..."
      class="mb-6"
      @change="query = $event"
    />
    <div v-if="!findedSnippets.length">
      Ничего не найдено
    </div>
    <div class="flex flex-col gap-3 w-max">
      <SnippetPreview
        v-for="snippet in findedSnippets"
        :key="snippet.item.id"
        :snippet="snippet.item"
        :title-highlight-ranges="snippet.titleHighlightRanges"
        :description-highlight-ranges="snippet.descriptionHighlightRanges"
      />
    </div>
  </div>
</template>

<script lang="ts" setup>
import createFuzzySearch from '@nozbe/microfuzz'
import type { SnippetsCollectionItem } from '@nuxt/content'
import { useDebounce } from '@vueuse/core'
import TextInput from './TextInput.vue'
import SnippetPreview from './SnippetPreview.vue'

const { snippets } = defineProps<{ snippets: SnippetsCollectionItem[] }>()

const query = ref('')
const debouncedQuery = useDebounce(query, 200)

const fuzzySearch = createFuzzySearch(snippets, {
  getText: (item: SnippetsCollectionItem) => [item.title, item.description],
})

const findedSnippets = computed(() => {
  if (!debouncedQuery.value) {
    return snippets.map(i => ({
      item: i,
      score: 1,
      titleHighlightRanges: [],
      descriptionHighlightRanges: [],
    }))
  }

  const searchResult = fuzzySearch(debouncedQuery.value)

  return searchResult.map((i) => {
    const [titleHighlightRanges, descriptionHighlightRanges] = i.matches

    return ({
      item: i.item,
      score: i.score,
      titleHighlightRanges: titleHighlightRanges || [],
      descriptionHighlightRanges: descriptionHighlightRanges || [],
    })
  })
})
</script>

<style>

</style>

// components/SnippetsSearch/SnippetsSearch.tsx
import { useFuzzySearchList } from '@nozbe/microfuzz/react';
import { SnippetPreview } from '../Snippet/SnippetPreview';
import { useState } from 'react';
import useDebounce from '@/hooks/useDebounce';
import { TextInput } from '../TextInput/TextInput';
import { Article } from 'content-collections';

type SnippetsSearchProps = {
  snippets: Omit<Article, 'component'>[]
}

export const SnippetsSearch: React.FC<SnippetsSearchProps> = ({
  snippets
}) => {
  const [query, setQuery] = useState('');
  const [debouncedQuery, setDebouncedQuery] = useState('');

  useDebounce(() => {
    setDebouncedQuery(query);
  }, 200, [query]);

  const filteredList = useFuzzySearchList({
    list: snippets,
    queryText: debouncedQuery,
    getText: (item) => [item.title, item.description],
    // arbitrary mapping function, takes `FuzzyResult<T>` as input
    mapResultItem: ({ 
      item,
      score, matches: [titleHighlightRanges, descriptionHighlightRanges]
    }) => ({ item, titleHighlightRanges, descriptionHighlightRanges })
  });
  
  const noResults = debouncedQuery.length > 0 && filteredList.length === 0;

  return (
    <div>
      <TextInput 
        value={query}
        placeholder="Поиск..."
        onChange={e => setQuery(e.target.value)}
        className="mb-6"
      />
      {noResults && <div>
        Ничего не найдено
      </div>}
      <div className='flex flex-col gap-3 w-max'>
        {filteredList.map(({ item, titleHighlightRanges, descriptionHighlightRanges }) => 
          <SnippetPreview
            key={item.path}
            snippet={item}
            titleHighlightRanges={titleHighlightRanges}
            descriptionHighlightRanges={descriptionHighlightRanges}
          />
        )}
      </div>
    </div>
  );
};
