// components/content/Accordion.vue
<template>
  <details
    class="details"
    :open="open"
    @change="toggle"
  >
    <summary class="summary">
      <span class="text-primary font-semibold select-none">
        {{ summary }}
      </span>

      <span>
        <SvgArrowdown
          width="12px"
          height="12px"
          class="icon"
        />
      </span>
    </summary>
    <span class="text-text/80">
      <slot />
    </span>
  </details>
</template>

<script lang="ts" setup>
import SvgArrowdown from '~/assets/icons/arrowdown.svg'

const { summary } = defineProps<{ summary: string }>()
const open = ref(false)

const toggle = () => {
  open.value = !open.value
}
</script>

<style scoped>
.summary {
  display: flex;
  align-items: center;
  gap: 0.375rem;
  cursor: pointer;

  &::-webkit-details-marker {
    display: none;
  }

  list-style: none;
}

.details {
  &[open] {
    .icon {
      transform: scaleY(-1);
    }
  }
}
</style>

// components/Accordion/Accordion.tsx
import classNames from "classnames";
import { FormEvent, useCallback, useState } from "react";
import styles from './Accordion.module.css';
import SvgArrowdown from "@/assets/icons/arrowdown.svg?react";

type DetailsProps = React.ComponentPropsWithoutRef<"details"> & {
  summary: React.ReactNode;
  children: React.ReactNode;
}

const Accordion: React.FC<DetailsProps> = ({ summary, children, ...props }) => {
  const [open, setOpen] = useState(false);

  const onToggle = useCallback((e: FormEvent<HTMLDetailsElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setOpen(value => !value);
  }, []);

  return (
    <details className={styles.details} open={open} onChange={onToggle} {...props}>
      <summary className={classNames(styles.summary)}>
        <span className="text-primary font-semibold select-none">
          {summary}
        </span>

        <span>
          <SvgArrowdown width={12} height={12} className={styles.icon} />
        </span>
      </summary>
      <span className="text-text/80">
        {children}
      </span>
    </details>
  );
};

export default Accordion;
