// app/blog/page.tsx
import { getAllArticles } from '@/helpers/blog';
import { BlogArticle } from '@/components/Article';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Блог - Трофимов Евгений',
  description: 'Статьи по веб-разработке - React, Node.js, Typescript',
}

export default async function Home() {
  const articles = await getAllArticles();

  return (
    <div className='flex flex-col gap-3'>
      {articles.map((article, index) =>
        <BlogArticle
          key={index}
          article={article}
        />
      )}
    </div>
  );
}

// pages/blog/index.vue
<template>
  <div class="flex flex-col gap-6">
    <ArticlePreview
      v-for="post in posts"
      :key="post.id"
      :article="post"
    />
  </div>
</template>

<script lang="ts" setup>
import ArticlePreview from '~/components/ArticlePreview.vue'

useSeoMeta({
  title: 'Блог - Трофимов Евгений',
})

const { data: posts } = await useAsyncData('blog', () => {
  return queryCollection('articles').all()
})
</script>
