// components/Tag.vue
<template>
  <component
    :is="is"
    class="rounded-3xl text-secondary inline-flex items-center text-body2 transition-colors focus-visible:ring-0 focus-visible:ring-offset-0 focus-visible:rounded-3xl"
    :class="{
      'px-3 py-[3px]': size === 'small',
      'px-3 py-[6px]': size === 'normal',
      'pl-[5px]!': !!icon,
      'bg-details/50': variant === 'filled',
      'border-2 border-details bg-transparent hover:border-transparent hover:bg-details hover:text-text focus-visible:bg-details focus-visible:border-transparent focus-visible:text-text': variant === 'outlined',
    }"
  >
    <component
      :is="icon"
      v-if="icon"
      class="w-[22px] h-[22px] mr-1.5"
    />
    <slot />
  </component>
</template>

<script lang="ts" setup>
import type { Component, SVGAttributes } from 'vue'

const { size = 'small', variant, is = 'div', icon } = defineProps<{
  size?: 'small' | 'normal'
  variant: 'filled' | 'outlined'
  is?: string | Component
  icon?: Component<SVGAttributes>
}>()
</script>

<style>

</style>

// components/Tag/Tag.tsx
import { DynamicHTMLProps } from "@/types/dynamicProps";
import classNames from "classnames";
import React, { ReactElement } from "react";
import { ReactNode, ElementType } from "react";

interface Props<T> {
  as?: T;
  children?: ReactNode;
  size?: 'small' | 'normal';
  variant: 'filled' | 'outlined'
  icon?: ReactElement;
}

const Tag = <T extends ElementType = "span">({
  as,
  children,
  size = 'normal',
  variant,
  icon,
  className,
  ...props
}: DynamicHTMLProps<Props<T>, T>) => {
  const Tag: ElementType = as || 'span';

  return (
    <Tag
      className={classNames(
        className,
        "rounded-3xl text-secondary inline-flex items-center text-body2 transition-colors focus-visible:ring-0 focus-visible:ring-offset-0 focus-visible:rounded-3xl",
        size === 'small' && 'px-3 py-[3px]',
        size === 'normal' && 'px-3 py-[6px]',
        icon && 'pl-[5px]!',
        variant === 'filled' && 'bg-details/50',
        variant === 'outlined' && 'border-2 border-details bg-transparent hover:border-transparent hover:bg-details hover:text-text focus-visible:bg-details focus-visible:border-transparent focus-visible:text-text'
      )}
      {...props}
    >
      {icon && React.cloneElement(icon, {
        height: 22,
        width: 22,
        className: classNames('mr-[5px]', icon.props?.className)
      })}
      {children}
    </Tag>
  );
};

export default Tag;
